name: secure_localizations_example
description: Test project for the encryption tool
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # This links the example to the package code in the folder above
  secure_localizations:
    path: ../

# Tool configuration
secure_localizations:

flutter:
  generate: true
